nginx:
  image: nginx
  ports:
   - "80:80"
  environment:
   - NGINX_PORT=80
  command: /bin/bash -c "echo Hello from Openmatics IT > /usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"
